language: c

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libarchive traildb/judy/judy; brew link --force libarchive; fi
  - pip install --user cpp-coveralls

addons:
  apt:
    packages:
    - libarchive-dev
    - libjudy-dev
    - pkg-config

script:
  - ./waf configure
  - ./waf build
  - ./waf test
  - ./waf test_cli

after_success:
  - COV=$(python -c 'import site; print "%s/bin/" % site.USER_BASE'); $COV/coveralls --include src --build-root build/test/
